using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;

namespace GibJohn.Models
{
    public class Registration
    {
        // Defines all the properties generated by registering, their constraints and their data types.
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string UserId { get; set; }
        public string Date { get; set; }
    }
}
